//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class SidescanMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/Sidescan";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public byte type;
        //  Packet Type, 0xE2 = Sonar 8 Bit
        public uint time;
        //  Ping time   [100 us]
        public byte frequency_id;
        //  Freq Id, currently 0x00
        public short gain;
        public ushort decimation;
        public float max_duration;
        //  Max travel time of outermost bins (s)
        public byte[] port_channel;
        public byte[] starboard_channel;
        public byte[] port_channel_phase_15_8;
        public byte[] port_channel_phase_7_0;
        public byte[] starboard_channel_phase_15_8;
        public byte[] starboard_channel_phase_7_0;
        public byte[] extra_channel;

        public SidescanMsg()
        {
            this.header = new Std.HeaderMsg();
            this.type = 0;
            this.time = 0;
            this.frequency_id = 0;
            this.gain = 0;
            this.decimation = 0;
            this.max_duration = 0.0f;
            this.port_channel = new byte[0];
            this.starboard_channel = new byte[0];
            this.port_channel_phase_15_8 = new byte[0];
            this.port_channel_phase_7_0 = new byte[0];
            this.starboard_channel_phase_15_8 = new byte[0];
            this.starboard_channel_phase_7_0 = new byte[0];
            this.extra_channel = new byte[0];
        }

        public SidescanMsg(Std.HeaderMsg header, byte type, uint time, byte frequency_id, short gain, ushort decimation, float max_duration, byte[] port_channel, byte[] starboard_channel, byte[] port_channel_phase_15_8, byte[] port_channel_phase_7_0, byte[] starboard_channel_phase_15_8, byte[] starboard_channel_phase_7_0, byte[] extra_channel)
        {
            this.header = header;
            this.type = type;
            this.time = time;
            this.frequency_id = frequency_id;
            this.gain = gain;
            this.decimation = decimation;
            this.max_duration = max_duration;
            this.port_channel = port_channel;
            this.starboard_channel = starboard_channel;
            this.port_channel_phase_15_8 = port_channel_phase_15_8;
            this.port_channel_phase_7_0 = port_channel_phase_7_0;
            this.starboard_channel_phase_15_8 = starboard_channel_phase_15_8;
            this.starboard_channel_phase_7_0 = starboard_channel_phase_7_0;
            this.extra_channel = extra_channel;
        }

        public static SidescanMsg Deserialize(MessageDeserializer deserializer) => new SidescanMsg(deserializer);

        private SidescanMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.type);
            deserializer.Read(out this.time);
            deserializer.Read(out this.frequency_id);
            deserializer.Read(out this.gain);
            deserializer.Read(out this.decimation);
            deserializer.Read(out this.max_duration);
            deserializer.Read(out this.port_channel, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.starboard_channel, sizeof(byte), deserializer.ReadLength());
            // FIELD ORDER IS THE WIRE FORMAT. The real driver's Sidescan.msg (measured from
            // the 2024-12-10 ISSS bag's own inline definition) puts extra_channel BEFORE the
            // four phase arrays; ours had it after. Serialization is positional, so the two
            // would have decoded each other's arrays into the wrong fields -- lengths and all
            // -- which is SETTLED §3c's "a message that changed since the recording decodes to
            // confident nonsense", except between our own two halves. Order below now matches
            // the real definition exactly:
            //   port_channel, starboard_channel, extra_channel,
            //   port_channel_phase_15_8, port_channel_phase_7_0,
            //   starboard_channel_phase_15_8, starboard_channel_phase_7_0
            deserializer.Read(out this.extra_channel, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.port_channel_phase_15_8, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.port_channel_phase_7_0, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.starboard_channel_phase_15_8, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.starboard_channel_phase_7_0, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.type);
            serializer.Write(this.time);
            serializer.Write(this.frequency_id);
            serializer.Write(this.gain);
            serializer.Write(this.decimation);
            serializer.Write(this.max_duration);
            serializer.WriteLength(this.port_channel);
            serializer.Write(this.port_channel);
            serializer.WriteLength(this.starboard_channel);
            serializer.Write(this.starboard_channel);
            // extra_channel BEFORE the phase arrays -- see the note in the deserializer.
            serializer.WriteLength(this.extra_channel);
            serializer.Write(this.extra_channel);
            serializer.WriteLength(this.port_channel_phase_15_8);
            serializer.Write(this.port_channel_phase_15_8);
            serializer.WriteLength(this.port_channel_phase_7_0);
            serializer.Write(this.port_channel_phase_7_0);
            serializer.WriteLength(this.starboard_channel_phase_15_8);
            serializer.Write(this.starboard_channel_phase_15_8);
            serializer.WriteLength(this.starboard_channel_phase_7_0);
            serializer.Write(this.starboard_channel_phase_7_0);
        }

        public override string ToString()
        {
            return "SidescanMsg: " +
            "\nheader: " + header.ToString() +
            "\ntype: " + type.ToString() +
            "\ntime: " + time.ToString() +
            "\nfrequency_id: " + frequency_id.ToString() +
            "\ngain: " + gain.ToString() +
            "\ndecimation: " + decimation.ToString() +
            "\nmax_duration: " + max_duration.ToString() +
            "\nport_channel: " + System.String.Join(", ", port_channel.ToList()) +
            "\nstarboard_channel: " + System.String.Join(", ", starboard_channel.ToList()) +
            "\nport_channel_phase_15_8: " + System.String.Join(", ", port_channel_phase_15_8.ToList()) +
            "\nport_channel_phase_7_0: " + System.String.Join(", ", port_channel_phase_7_0.ToList()) +
            "\nstarboard_channel_phase_15_8: " + System.String.Join(", ", starboard_channel_phase_15_8.ToList()) +
            "\nstarboard_channel_phase_7_0: " + System.String.Join(", ", starboard_channel_phase_7_0.ToList()) +
            "\nextra_channel: " + System.String.Join(", ", extra_channel.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
