using System.Reflection;
using UnityEngine;
using ROS.Core;

namespace VehicleComponents.Sensors
{
    /// <summary>
    /// Deep Vision side scan sonar (DE340/DE680 family, as on SAM 2.2): one sonar unit
    /// with TWO transducers (port + starboard), switchable between two operating
    /// frequencies. The underlying Sonar runs in SSS mode with two beams, and SSS_Pub
    /// publishes separate port_channel / starboard_channel arrays — i.e. left/right
    /// data ready for waterfall images. With Interferometric on, per-bin angle bytes
    /// are also published, so point clouds can be built downstream.
    ///
    ///   LF 340 kHz: 15-200 m/side, 20 cm bins  — wide-area search      (~3 Hz ping)
    ///   HF 680 kHz: 10-100 m/side,  5 cm bins  — high-res imaging      (~7 Hz ping)
    ///
    /// Mode/interferometric take effect when entering Play (the Sonar sizes its bucket
    /// arrays in Awake); switching mid-run needs a Stop/Play, same as re-configuring
    /// the real unit's recording session.
    /// </summary>
    [DefaultExecutionOrder(-100)] // apply the preset before Sonar.Awake sizes its arrays
    [RequireComponent(typeof(Sonar))]
    [AddComponentMenu("Smarc/Sensor/DeepVisionSSS")]
    public class DeepVisionSSS : MonoBehaviour
    {
        public enum FrequencyMode { LF340, HF680 }

        [Tooltip("Operating frequency (both transducers switch together). LF340: 200 m/side wide-area. HF680: 100 m/side high-res. Applied at Play start.")]
        public FrequencyMode Mode = FrequencyMode.HF680;

        [Tooltip("Interferometric mode: publish per-bin elevation angles alongside the port/starboard echo channels, enabling point clouds. Off = plain waterfall echoes only.")]
        public bool Interferometric = true;

        // THE MOUNT GEOMETRY IS OWNED HERE, because leaving it un-owned has now cost three
        // sessions (2026-08-16 twice, 2026-08-17). SAMSensorsV2.prefab is GENERATED by
        // SamV2PerceptionBuilder from SAMSensors.prefab, whose side scan is the v1 mount
        // (tilt 45 / breadth 45 -> off-nadir 0..45 deg). This component set every other
        // DeepVision parameter and left these two to be inherited, so every press of
        // "SMARC/Build SAM v2 Perception Prefabs" silently overwrote the committed
        // tilt 0 / breadth 60 with the v1 values -- which was blamed on "Unity
        // re-serializing the prefab" when it was in fact our own generator, deterministically.
        // Values below ARE the committed ones (git show HEAD:...SAMSensorsV2.prefab), so this
        // changes no number; it only makes the number survive a rebuild.
        [Tooltip("Downward tilt of the transducer mount, deg. With BeamBreadthDeg it fixes the off-nadir coverage [90-tilt-breadth, 90-tilt]; a side scan sees nothing at nadir.")]
        public float TiltAngleDeg = 0f;

        [Tooltip("Vertical opening angle of the beam, deg. 60 is the DE680D figure recorded in sss_geometry.SIM_BEAM_AS_SHIPPED -- NOT read off a DeepVision datasheet by anyone in this repo.")]
        public float BeamBreadthDeg = 60f;

        void OnValidate() { Apply(); }
        void Awake() { Apply(); }

        public void Apply()
        {
            var sonar = GetComponent<Sonar>();
            if (sonar == null) return;

            float pingHz;
            if (Mode == FrequencyMode.LF340)
            {
                sonar.MaxRange = 200f;
                sonar.NumBucketsPerBeam = 1000; // 20 cm range bins
                sonar.NumRaysPerBeam = 256;
                pingHz = 3f; // two-way travel at 200 m ~ 0.27 s
            }
            else
            {
                sonar.MaxRange = 100f;
                sonar.NumBucketsPerBeam = 2000; // 5 cm range bins
                sonar.NumRaysPerBeam = 512;
                pingHz = 7f;
            }
            sonar.isInterferometric = Interferometric;
            sonar.frequency = pingHz;
            sonar.TiltAngleDeg = TiltAngleDeg;
            sonar.BeamBreadthDeg = BeamBreadthDeg;

            // Match the SSS publisher rate to the ping rate. Reflection because the
            // publisher classes are internal; ROSPublisher<T>.frequency is public.
            foreach (var mb in GetComponents<MonoBehaviour>())
            {
                if (mb == null || mb == this || !(mb is ROSBehaviour rosb)) continue;
                if (!rosb.topic.Contains("sidescan")) continue;
                var f = mb.GetType().GetField("frequency", BindingFlags.Public | BindingFlags.Instance);
                if (f != null && f.FieldType == typeof(float)) f.SetValue(mb, pingHz);
            }
        }
    }
}
