using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

using GeoRef;

/// <summary>
/// Builds the Kristineberg site assets from the data produced by
/// data-cube/scripts/kristineberg-site/ :
///
///   KristinebergTerrain.asset   TerrainData from kristineberg_heightmap.r16
///   kristineberg_dock.asset     dock mesh (the quay face — vertical/overhanging,
///                               which a heightmap cannot represent)
///   kristineberg_buildings.asset
///   KristinebergWorld.prefab    cloned from AskoWorld.prefab so Ocean/Sky/Sun come
///                               from the proven Askö setup; only the terrain,
///                               structures and GLOBALREF differ
///   KristinebergEmpty.unity     the scene, modelled on AskoEmpty.unity
///
/// Frame: Unity +X = UTM 32N easting, +Z = UTM 32N northing, origin = K-berg origo
/// (58.249721 N, 11.44624 E). Water plane at y = 0. Provenance and the measurements
/// behind every number: _test_sites/Kristineberg/KRISTINEBERG_SITE.md
///
/// Vertices in the .smesh files are ALREADY in Unity scene coordinates — they are
/// assigned verbatim. No model importer is involved, so no axis convention can be
/// silently misapplied (the Beckholmen COLLADA lesson).
///
/// Run from menu: SMARC -> Build Kristineberg Site
/// Safe to re-run; overwrites the generated assets.
/// </summary>
public static class KristinebergSiteBuilder
{
    const string DataDir = "Packages/com.smarc.assets/Runtime/Terrain/Kristineberg";
    const string OutDir = "Packages/com.smarc.assets/Runtime/Terrain/Kristineberg";
    const string PrefabDir = "Packages/com.smarc.assets/Runtime/Prefabs/Environment/GeoReferenced";
    const string AskoWorldPath = PrefabDir + "/AskoWorld.prefab";
    const string WorldPrefabPath = PrefabDir + "/KristinebergWorld.prefab";
    const string TerrainAssetPath = OutDir + "/KristinebergTerrain.asset";
    const string ScenePath = "Assets/Scenes/KristinebergEmpty.unity";
    const string MatDir = "Packages/com.smarc.assets/Runtime/Materials";
    const string MatTerrain = MatDir + "/DefaultHDTerrainLitMaterial.mat";  // same as Askö's terrain
    const string MatConcrete = MatDir + "/Concrete-ish.mat";
    const string MatDefault = MatDir + "/Default.mat";
    const string TileMaterialPath = MatDir + "/2DMapMaterial.mat";        // the one AskoWorld's tiler uses

    // ---- manifest mirror of kristineberg_unity.json --------------------------
    [Serializable] public class MeshEntry { public string name, file, collider; public int verts, tris; public string[] colliderChunks; }
    [Serializable] public class BuoyEntry { public string name; public float x; public float z; }
    [Serializable] public class CameraEntry { public string name, note; public float x, y, z, seabed, namedDepth; }
    [Serializable]
    public class LaunchEntry
    {
        public float x, y, z, depth_m;
        public string vehicle_prefab, vehicle_name, gui_prefab;
    }
    /// <summary>
    /// What the side scan has to be able to SEE for the algae-farm inspection mission
    /// (2026-08-16). Generated by sam_farm_inspection/sss_geometry.py via
    /// make_unity_manifest.py — the two angles are a REQUIREMENT derived from the rope
    /// depth in the farm prior, not a copy of any prefab's settings, so the verifier
    /// keeps meaning the same thing if someone re-tunes the beam.
    /// </summary>
    [Serializable]
    public class SssEntry
    {
        public string topic, asShippedNote;
        public bool requireInterferometric, asShippedFlyable;
        public float ropeDepth, laneStandoff, minScanDepth, depthControlError, beamMargin;
        public float maxOffNadirMinDeg;   // the beam must reach AT LEAST this far off nadir
        public float minOffNadirMaxDeg;   // the nadir gap must be no wider than this
    }
    [Serializable]
    public class Manifest
    {
        public string generatedUtc, site, heightmapFile, utmBand;
        public double anchorLat, anchorLon, anchorUtmEasting, anchorUtmNorthing;
        public int utmZone, heightmapRes;
        public float sizeX, sizeY, sizeZ, posX, posY, posZ, waterPlaneY;
        public MeshEntry[] meshes;
        public BuoyEntry[] buoys;
        public CameraEntry[] cameras;
        public LaunchEntry launch;
        public SssEntry sss;
    }

    [MenuItem("SMARC/Build Kristineberg Site")]
    public static void Build()
    {
        try
        {
            var manifestPath = DataDir + "/kristineberg_unity.json";
            var json = ReadTextAsset(manifestPath);
            if (json == null)
            {
                EditorUtility.DisplayDialog("Kristineberg",
                    "Could not read " + manifestPath + "\n\nRun the pipeline first:\n" +
                    "  python3 data-cube/scripts/kristineberg-site/build_heightmap.py\n" +
                    "  python3 data-cube/scripts/kristineberg-site/export_meshes.py\n" +
                    "  python3 data-cube/scripts/kristineberg-site/make_unity_manifest.py", "OK");
                return;
            }
            var m = JsonUtility.FromJson<Manifest>(json);
            Debug.Log($"[Kristineberg] manifest generated {m.generatedUtc}; terrain {m.sizeX}x{m.sizeZ} m, " +
                      $"heightmap {m.heightmapRes}, y {m.posY}..{m.posY + m.sizeY}");

            EditorUtility.DisplayProgressBar("Kristineberg", "Building terrain…", 0.1f);
            var terrainData = BuildTerrain(m);

            EditorUtility.DisplayProgressBar("Kristineberg", "Building structure meshes…", 0.45f);
            var meshes = BuildMeshes(m);

            EditorUtility.DisplayProgressBar("Kristineberg", "Building world prefab…", 0.75f);
            var prefab = BuildWorldPrefab(m, terrainData, meshes);

            EditorUtility.DisplayProgressBar("Kristineberg", "Building scene…", 0.9f);
            BuildScene(prefab, m);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[Kristineberg] done. Open " + ScenePath +
                      " and run SMARC -> Verify Kristineberg Site.");
        }
        finally
        {
            EditorUtility.ClearProgressBar();
        }
    }

    // -------------------------------------------------------------------------
    static string ReadTextAsset(string assetPath)
    {
        var full = AssetPathToFull(assetPath);
        return File.Exists(full) ? File.ReadAllText(full) : null;
    }

    /// <summary>Resolve an Assets/ or Packages/ path to a real filesystem path.</summary>
    public static string AssetPathToFullPublic(string assetPath) => AssetPathToFull(assetPath);

    static string AssetPathToFull(string assetPath)
    {
        // Packages/... paths are not under Application.dataPath; resolve properly.
        var pi = UnityEditor.PackageManager.PackageInfo.FindForAssetPath(assetPath);
        if (pi != null)
            return Path.Combine(pi.resolvedPath, assetPath.Substring(("Packages/" + pi.name + "/").Length));
        return Path.Combine(Application.dataPath, assetPath.Substring("Assets/".Length));
    }

    static TerrainData BuildTerrain(Manifest m)
    {
        var raw = AssetPathToFull(DataDir + "/" + m.heightmapFile);
        if (!File.Exists(raw)) throw new FileNotFoundException("heightmap not found: " + raw);

        int res = m.heightmapRes;
        var bytes = File.ReadAllBytes(raw);
        long expected = (long)res * res * 2;
        if (bytes.LongLength != expected)
            throw new Exception($"heightmap size {bytes.LongLength} != expected {expected} for res {res}");

        // r16: uint16 little-endian, row 0 = SOUTH, col 0 = WEST.
        // Unity's SetHeights takes [y, x] where y indexes +Z. Same order, direct copy.
        var heights = new float[res, res];
        int k = 0;
        for (int z = 0; z < res; z++)
            for (int x = 0; x < res; x++, k += 2)
                heights[z, x] = (bytes[k] | (bytes[k + 1] << 8)) / 65535f;

        var td = AssetDatabase.LoadAssetAtPath<TerrainData>(TerrainAssetPath);
        bool isNew = td == null;
        if (isNew) td = new TerrainData();
        td.name = "KristinebergTerrain";
        td.heightmapResolution = res;
        td.size = new Vector3(m.sizeX, m.sizeY, m.sizeZ);
        td.SetHeights(0, 0, heights);
        if (isNew) AssetDatabase.CreateAsset(td, TerrainAssetPath);
        else EditorUtility.SetDirty(td);

        ApplySplat(td);

        Debug.Log($"[Kristineberg] terrain {res}x{res}, size {td.size}, " +
                  $"seabed reaches {m.posY:F1} m, water plane at y=0 " +
                  $"(normalised {(0f - m.posY) / m.sizeY:F4})");
        return td;
    }

    [Serializable] public class SplatLayer { public int channel; public string name, texture; public float[] base_rgb; public float coverage; }
    [Serializable] public class SplatManifest { public string control_map; public int control_resolution; public float tile_size_m; public SplatLayer[] layers; }

    /// <summary>
    /// Surface the terrain from the control map derived in build_splatmap.py. The
    /// classification (seabed / shore / rock / vegetation) comes from measured depth and
    /// slope; only the textures themselves are placeholders.
    /// </summary>
    static void ApplySplat(TerrainData td)
    {
        var manifestPath = AssetPathToFull(DataDir + "/kristineberg_splat.json");
        if (!File.Exists(manifestPath))
        {
            Debug.LogWarning("[Kristineberg] no kristineberg_splat.json — terrain left untextured. " +
                             "Run build_splatmap.py.");
            return;
        }
        var sm = JsonUtility.FromJson<SplatManifest>(File.ReadAllText(manifestPath));

        var layers = new TerrainLayer[sm.layers.Length];
        for (int i = 0; i < sm.layers.Length; i++)
        {
            var L = sm.layers[i];
            var texPath = DataDir + "/" + L.texture;
            var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(texPath);
            if (tex == null) { Debug.LogWarning("[Kristineberg] missing texture " + texPath); return; }
            var layerPath = OutDir + "/Kristineberg_" + L.name + ".terrainlayer";
            var layer = AssetDatabase.LoadAssetAtPath<TerrainLayer>(layerPath);
            if (layer == null)
            {
                layer = new TerrainLayer();
                AssetDatabase.CreateAsset(layer, layerPath);
            }
            layer.diffuseTexture = tex;
            layer.tileSize = new Vector2(sm.tile_size_m, sm.tile_size_m);
            layer.tileOffset = Vector2.zero;
            EditorUtility.SetDirty(layer);
            layers[i] = layer;
        }
        td.terrainLayers = layers;

        // RAW uint8 [row][col][layer], not a PNG: an RGBA image caps the scheme at four layers,
        // and the seabed needs sand / mud / rock separated. Reading the raw bytes also keeps
        // import settings (compression, sRGB, readability) from altering the weights.
        var ctrlPath = AssetPathToFull(DataDir + "/" + sm.control_map);
        if (!File.Exists(ctrlPath))
        { Debug.LogError("[Kristineberg] control map not found: " + ctrlPath + " — run build_splatmap.py"); return; }
        var raw = File.ReadAllBytes(ctrlPath);
        int n = sm.control_resolution;
        long expect = (long)n * n * layers.Length;
        if (raw.LongLength != expect)
        {
            Debug.LogError($"[Kristineberg] control map is {raw.LongLength} bytes, expected " +
                           $"{expect} for {n}x{n}x{layers.Length} — regenerate it");
            return;
        }

        td.alphamapResolution = n;
        var maps = new float[n, n, layers.Length];
        int k = 0;
        for (int y = 0; y < n; y++)
            for (int x = 0; x < n; x++)
            {
                float s = 0f;
                for (int l = 0; l < layers.Length; l++) s += raw[k + l];
                if (s <= 0f) maps[y, x, 0] = 1f;
                else for (int l = 0; l < layers.Length; l++) maps[y, x, l] = raw[k + l] / s;
                k += layers.Length;
            }
        td.SetAlphamaps(0, 0, maps);
        Debug.Log($"[Kristineberg] splat: {layers.Length} layers at {n}x{n}, tile {sm.tile_size_m} m " +
                  $"({string.Join(", ", System.Array.ConvertAll(sm.layers, l => l.name))})");
    }

    /// <summary>
    /// Read a .smesh into a Mesh asset. Used for the collider chunks, which need to be real
    /// assets so the prefab can reference them.
    /// </summary>
    static Mesh LoadSMeshAsset(string assetPath, string meshName)
    {
        var full = AssetPathToFull(assetPath);
        if (!File.Exists(full)) { Debug.LogWarning("[Kristineberg] missing " + full); return null; }
        using var fs = new FileStream(full, FileMode.Open, FileAccess.Read);
        using var br = new BinaryReader(fs);
        if (new string(br.ReadChars(4)) != "SMSH") { Debug.LogError("bad magic in " + assetPath); return null; }
        br.ReadUInt32();
        int nameLen = (int)br.ReadUInt32(); br.ReadBytes(nameLen);
        int nv = (int)br.ReadUInt32(), nt = (int)br.ReadUInt32();
        for (int i = 0; i < 6; i++) br.ReadSingle();
        int nsub = (int)br.ReadUInt32();
        for (int s = 0; s < nsub; s++)
        { int sl = (int)br.ReadUInt32(); br.ReadBytes(sl); br.ReadUInt32(); br.ReadUInt32(); }
        var verts = new Vector3[nv];
        for (int i = 0; i < nv; i++) verts[i] = new Vector3(br.ReadSingle(), br.ReadSingle(), br.ReadSingle());
        var tris = new int[nt * 3];
        for (int i = 0; i < tris.Length; i++) tris[i] = (int)br.ReadUInt32();

        var mesh = new Mesh { name = meshName };
        if (nv > 65535) mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
        mesh.vertices = verts; mesh.triangles = tris;
        mesh.RecalculateNormals(); mesh.RecalculateBounds();

        var outPath = OutDir + "/" + meshName + ".asset";
        var existing = AssetDatabase.LoadAssetAtPath<Mesh>(outPath);
        if (existing == null) AssetDatabase.CreateAsset(mesh, outPath);
        else { EditorUtility.CopySerialized(mesh, existing); mesh = existing; EditorUtility.SetDirty(mesh); }
        return mesh;
    }

    static readonly Dictionary<string, string[]> subMeshNames = new Dictionary<string, string[]>();

    static Dictionary<string, Mesh> BuildMeshes(Manifest m)
    {
        var result = new Dictionary<string, Mesh>();
        subMeshNames.Clear();
        if (m.meshes == null) return result;

        foreach (var me in m.meshes)
        {
            var path = AssetPathToFull(DataDir + "/" + me.file);
            if (!File.Exists(path)) { Debug.LogWarning("[Kristineberg] missing mesh " + path); continue; }

            using var fs = new FileStream(path, FileMode.Open, FileAccess.Read);
            using var br = new BinaryReader(fs);
            var magic = new string(br.ReadChars(4));
            if (magic != "SMSH") throw new Exception("bad magic in " + me.file + ": " + magic);
            uint version = br.ReadUInt32();
            if (version != 2) throw new Exception($"{me.file} is format v{version}; this builder reads v2");
            int nameLen = (int)br.ReadUInt32();
            br.ReadBytes(nameLen);                            // name
            int nv = (int)br.ReadUInt32();
            int nt = (int)br.ReadUInt32();
            for (int i = 0; i < 6; i++) br.ReadSingle();      // bounds

            int nsub = (int)br.ReadUInt32();
            var subNames = new string[nsub];
            var subStart = new int[nsub];
            var subCount = new int[nsub];
            for (int s = 0; s < nsub; s++)
            {
                int sl = (int)br.ReadUInt32();
                subNames[s] = System.Text.Encoding.UTF8.GetString(br.ReadBytes(sl));
                subStart[s] = (int)br.ReadUInt32();
                subCount[s] = (int)br.ReadUInt32();
            }

            var verts = new Vector3[nv];
            for (int i = 0; i < nv; i++)
                verts[i] = new Vector3(br.ReadSingle(), br.ReadSingle(), br.ReadSingle());
            var tris = new int[nt * 3];
            for (int i = 0; i < tris.Length; i++) tris[i] = (int)br.ReadUInt32();

            var mesh = new Mesh { name = "kristineberg_" + me.name };
            if (nv > 65535) mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.vertices = verts;
            mesh.subMeshCount = nsub;
            for (int s = 0; s < nsub; s++)
            {
                var sub = new int[subCount[s] * 3];
                Array.Copy(tris, subStart[s] * 3, sub, 0, sub.Length);
                mesh.SetTriangles(sub, s);
            }
            // Winding is already Unity-correct in the .smesh (the source->Unity map is a
            // mirror and the exporter reverses it), so normals come out pointing OUTWARD.
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            subMeshNames[me.name] = subNames;

            var outPath = OutDir + "/kristineberg_" + me.name + ".asset";
            var existing = AssetDatabase.LoadAssetAtPath<Mesh>(outPath);
            if (existing == null) AssetDatabase.CreateAsset(mesh, outPath);
            else { EditorUtility.CopySerialized(mesh, existing); mesh = existing; EditorUtility.SetDirty(mesh); }

            result[me.name] = mesh;
            Debug.Log($"[Kristineberg] mesh {me.name}: {nv:N0} verts, {nt:N0} tris, bounds {mesh.bounds}");
        }
        return result;
    }

    /// <summary>
    /// Site materials, generated once and then left alone so they can be tweaked by hand.
    /// Colours are read off Ivan's 2026-08-16 drone photos of the station: terracotta pantile
    /// roofs, white and cream painted timber, red falu boathouses, concrete quay. Approximate
    /// on purpose — this is a stand-in until photogrammetry supplies real texture.
    /// </summary>
    static Material MaterialFor(string meshName, string subName)
    {
        string key = meshName == "dock" ? "Quay" : (subName == "roof" ? "Roof" : "Wall");
        var path = OutDir + "/Kristineberg_" + key + ".mat";
        var existing = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (existing != null) return existing;                 // never clobber hand-tuning

        var template = AssetDatabase.LoadAssetAtPath<Material>(MatDefault);
        var mat = template != null ? new Material(template)
                                   : new Material(Shader.Find("HDRP/Lit"));
        mat.name = "Kristineberg_" + key;
        Color c = key == "Roof" ? new Color(0.62f, 0.24f, 0.15f)    // terracotta pantile
                : key == "Wall" ? new Color(0.90f, 0.89f, 0.85f)    // white/cream painted timber
                                : new Color(0.62f, 0.60f, 0.57f);   // concrete quay
        foreach (var p in new[] { "_BaseColor", "_Color", "_BaseColorMap" })
            if (mat.HasProperty(p) && p != "_BaseColorMap") mat.SetColor(p, c);
        if (mat.HasProperty("_Smoothness")) mat.SetFloat("_Smoothness", key == "Roof" ? 0.25f : 0.15f);
        if (mat.HasProperty("_Metallic")) mat.SetFloat("_Metallic", 0f);
        AssetDatabase.CreateAsset(mat, path);
        Debug.Log($"[Kristineberg] created material {path} (edit it freely — the builder will not overwrite it)");
        return mat;
    }

    static GameObject BuildWorldPrefab(Manifest m, TerrainData td, Dictionary<string, Mesh> meshes)
    {
        // Clone Askö's world so Ocean, Sun and Sky/Fog come from a setup that already
        // works, rather than being reassembled from memory.
        var asko = AssetDatabase.LoadAssetAtPath<GameObject>(AskoWorldPath);
        if (asko == null) throw new FileNotFoundException("AskoWorld.prefab not found at " + AskoWorldPath);

        var root = (GameObject)PrefabUtility.InstantiatePrefab(asko);
        PrefabUtility.UnpackPrefabInstance(root, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
        root.name = "KristinebergWorld";

        // Drop anything Askö-specific: its terrain instance and any leftover children
        // that are not the environment essentials we want to keep.
        var keep = new HashSet<string> { "Ocean", "Sun", "Sky and Fog Global Volume" };
        for (int i = root.transform.childCount - 1; i >= 0; i--)
        {
            var c = root.transform.GetChild(i).gameObject;
            bool isGlobalRef = c.GetComponent<GlobalReferencePoint>() != null;
            if (isGlobalRef || !keep.Contains(c.name))
            {
                if (isGlobalRef) { UnityEngine.Object.DestroyImmediate(c); continue; }
                UnityEngine.Object.DestroyImmediate(c);
            }
        }

        // --- GLOBALREF at the scene origin, carrying the anchor -----------------
        var gref = new GameObject("GLOBALREF - KristinebergOrigo");
        gref.transform.SetParent(root.transform, false);
        gref.transform.localPosition = Vector3.zero;
        var grp = gref.AddComponent<GlobalReferencePoint>();
        grp.OriginMode = OriginMode.LatLon;
        grp.UnityCoordinateFrame = UnityCoordinateFrame.UTM;
        grp.Lat = m.anchorLat;
        grp.Lon = m.anchorLon;
        // Force the UTM fields to populate; OnValidate does this in the editor.
        var so = new SerializedObject(grp);
        so.ApplyModifiedProperties();
        grp.SendMessage("OnValidate", SendMessageOptions.DontRequireReceiver);
        // Askö drapes orthophoto tiles over its terrain through this; same component, same
        // settings. The WMS URL/layer come from the per-machine WMSSettings.yaml the
        // component writes on first run, so nothing site-specific is baked into the prefab.
        var tiler = gref.AddComponent<WMSTiler>();
        tiler.TileMaterial = AssetDatabase.LoadAssetAtPath<Material>(TileMaterialPath);
        tiler.Radius = 1000;
        tiler.TileSizePx = 400;
        tiler.TileSizeMeters = 256;
        if (tiler.TileMaterial == null)
            Debug.LogWarning("[Kristineberg] tile material not found at " + TileMaterialPath);

        Debug.Log($"[Kristineberg] GLOBALREF lat/lon {grp.Lat}, {grp.Lon} -> " +
                  $"CoordinateSharp UTM {grp.UTMZone}{grp.UTMBand} {grp.UTMEasting:F2} {grp.UTMNorthing:F2}" +
                  $"  | pyproj said {m.utmZone}{m.utmBand} {m.anchorUtmEasting:F2} {m.anchorUtmNorthing:F2}");
        if (grp.UTMZone != m.utmZone || grp.UTMBand != m.utmBand)
            Debug.LogError($"[Kristineberg] UTM ZONE/BAND MISMATCH: Unity says {grp.UTMZone}{grp.UTMBand}, " +
                           $"pipeline assumed {m.utmZone}{m.utmBand}. The scene frame is wrong.");
        double de = grp.UTMEasting - m.anchorUtmEasting, dn = grp.UTMNorthing - m.anchorUtmNorthing;
        if (Math.Abs(de) > 1.0 || Math.Abs(dn) > 1.0)
            Debug.LogWarning($"[Kristineberg] CoordinateSharp/pyproj UTM differ by ({de:F2}, {dn:F2}) m — " +
                             "everything georeferenced will carry that offset.");

        // --- terrain -------------------------------------------------------------
        var terrainGO = Terrain.CreateTerrainGameObject(td);
        terrainGO.name = "KristinebergTerrain";
        terrainGO.transform.SetParent(root.transform, false);
        terrainGO.transform.localPosition = new Vector3(m.posX, m.posY, m.posZ);
        terrainGO.transform.localScale = Vector3.one;   // never scale a georeferenced terrain
        var terrainMat = AssetDatabase.LoadAssetAtPath<Material>(MatTerrain);
        if (terrainMat != null) terrainGO.GetComponent<Terrain>().materialTemplate = terrainMat;
        else Debug.LogWarning("[Kristineberg] terrain material not found at " + MatTerrain);
        // The seabed itself must have a sonar signature. Without a physics material the
        // TerrainCollider returns Sonar.cs's 0.5 default and label 0 (unclassified) — i.e. the
        // bottom reads as "something unidentified" on every ping. Mud (0.20, label 1) is the
        // honest default for a soft fjord bottom; rock outcrops are dressed on top separately.
        var tc = terrainGO.GetComponent<TerrainCollider>();
        var physMud = AssetDatabase.LoadAssetAtPath<PhysicsMaterial>(
            "Packages/com.smarc.assets/Runtime/Materials/Physic/Mud.physicMaterial");
        if (tc != null && physMud != null) tc.sharedMaterial = physMud;
        else Debug.LogWarning("[Kristineberg] could not set Mud on the TerrainCollider — " +
                              "the seabed will read as unclassified on sonar");

        // --- structure meshes ----------------------------------------------------
        foreach (var kv in meshes)
        {
            var go = new GameObject("Kristineberg_" + kv.Key);
            go.transform.SetParent(root.transform, false);
            go.transform.localPosition = Vector3.zero;   // vertices are already in scene coords
            go.AddComponent<MeshFilter>().sharedMesh = kv.Value;
            var mr = go.AddComponent<MeshRenderer>();
            var names = subMeshNames.TryGetValue(kv.Key, out var sn) ? sn : new[] { "all" };
            var mats = new Material[names.Length];
            for (int s = 0; s < names.Length; s++) mats[s] = MaterialFor(kv.Key, names[s]);
            mr.sharedMaterials = mats;

            // Collider: one MeshCollider unless the mesh would trip PhysX's 2^21 INDEX limit,
            // in which case the exporter has already split it on component boundaries. This
            // matters because an over-cap collider can go SILENTLY DEAD — no error, no raycast
            // hits, and an empty sonar cloud reads as "obstacle clear" (SETTLED, Beckholmen).
            var entry = System.Array.Find(m.meshes, e => e.name == kv.Key);
            var chunks = entry == null ? null : entry.colliderChunks;
            if (chunks != null && chunks.Length > 0)
            {
                int made = 0;
                for (int ci = 0; ci < chunks.Length; ci++)
                {
                    var cm = LoadSMeshAsset(DataDir + "/" + chunks[ci],
                                            $"kristineberg_{kv.Key}_col{ci}");
                    if (cm == null) continue;
                    var cgo = new GameObject($"collider_{ci}");
                    cgo.transform.SetParent(go.transform, false);
                    cgo.AddComponent<MeshCollider>().sharedMesh = cm;
                    made++;
                }
                Debug.Log($"[Kristineberg] {kv.Key}: collider split into {made} chunks — a single " +
                          $"mesh would be {entry.tris * 3:N0} indices against PhysX's 2,097,152 cap");
            }
            else go.AddComponent<MeshCollider>().sharedMesh = kv.Value;
        }

        // --- surveyed buoy markers ----------------------------------------------
        // The algae-farm buoys are the only independently surveyed points at this site,
        // so they stay in the scene as the standing georeference check (and as the
        // reference frame for the historical-track session).
        if (m.buoys != null && m.buoys.Length > 0)
        {
            var holder = new GameObject("SurveyedBuoys (verification)");
            holder.transform.SetParent(root.transform, false);
            foreach (var b in m.buoys)
            {
                var marker = new GameObject($"Buoy_{b.name}");
                marker.transform.SetParent(holder.transform, false);
                marker.transform.localPosition = new Vector3(b.x, 0f, b.z);
            }
            Debug.Log($"[Kristineberg] {m.buoys.Length} surveyed buoy markers placed at y=0");
        }

        // --- synthetic twins of the two live observatory cameras ----------------
        // Kristineberg streams "Fjordens öga" from 5 m and 22 m at Långgap. Putting cameras at
        // the matching spots makes the sim directly comparable against a real feed — the
        // cheapest honest test of whether the underwater rendering and the seabed dressing
        // look like the actual fjord.
        if (m.cameras != null && m.cameras.Length > 0)
        {
            var camHolder = new GameObject("ObservatoryCameras (live-feed twins)");
            camHolder.transform.SetParent(root.transform, false);
            foreach (var c in m.cameras)
            {
                var go = new GameObject(c.name);
                go.transform.SetParent(camHolder.transform, false);
                go.transform.localPosition = new Vector3(c.x, c.y, c.z);
                // Looking slightly down and out over the bottom, which is how a fixed
                // observatory camera on a frame is aimed.
                go.transform.localRotation = Quaternion.Euler(12f, 200f, 0f);
                var cam = go.AddComponent<Camera>();
                cam.nearClipPlane = 0.05f;
                cam.farClipPlane = 60f;             // underwater visibility, not a landscape lens
                cam.fieldOfView = 70f;
                cam.enabled = false;                // off: they are reference views, not the game view
                Debug.Log($"[Kristineberg] {c.name} at ({c.x:F0}, {c.y:F2}, {c.z:F0}), " +
                          $"seabed {c.seabed:F2} m vs named {c.namedDepth:F0} m — {c.note}");
            }
        }

        var prefab = PrefabUtility.SaveAsPrefabAsset(root, WorldPrefabPath);
        UnityEngine.Object.DestroyImmediate(root);
        Debug.Log("[Kristineberg] world prefab -> " + WorldPrefabPath);
        return prefab;
    }

    static void BuildScene(GameObject worldPrefab, Manifest m)
    {
        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        var world = (GameObject)PrefabUtility.InstantiatePrefab(worldPrefab);
        world.transform.position = Vector3.zero;

        // Vehicle + GUI, exactly the pair AskoEmpty instances, at a launch point measured on
        // the carved terrain (4.7 m of water, 44 m off the quay).
        if (m.launch != null && !string.IsNullOrEmpty(m.launch.vehicle_prefab))
        {
            var pos = new Vector3(m.launch.x, m.launch.y, m.launch.z);
            var vp = AssetDatabase.LoadAssetAtPath<GameObject>(m.launch.vehicle_prefab);
            if (vp != null)
            {
                var v = (GameObject)PrefabUtility.InstantiatePrefab(vp);
                // The GameObject's name prefixes every ROS topic and tf frame at runtime, and
                // ROS names cannot contain '.', so this is not cosmetic — it must match the
                // namespace the bringup uses.
                v.name = m.launch.vehicle_name;
                v.transform.position = pos;
                Debug.Log($"[Kristineberg] {v.name} at {pos} over {m.launch.depth_m:F2} m of water");
            }
            else Debug.LogWarning("[Kristineberg] vehicle prefab not found: " + m.launch.vehicle_prefab);

            var gp = AssetDatabase.LoadAssetAtPath<GameObject>(m.launch.gui_prefab);
            if (gp != null)
            {
                var g = (GameObject)PrefabUtility.InstantiatePrefab(gp);
                g.name = "GUI";
                g.transform.position = pos + new Vector3(0, 10f, 0);
            }
            else Debug.LogWarning("[Kristineberg] GUI prefab not found: " + m.launch.gui_prefab);

            // The mission WP hoop — the visual the dry dock has had since 2026-08-09, showing
            // which waypoint the vehicle is flying to right now. Site-agnostic: it reads
            // GLOBALREF, so it needs no Kristineberg constants. Idempotent, and also available
            // on its own menu item (SMARC -> Add Mission WP Hoop to Open Scene) so a scene that
            // already exists does not have to be rebuilt to gain one.
            MissionWPHoopSetup.Ensure(m.launch.vehicle_name);
        }

        // The algae farm, if it has been built (SMARC -> Build Kristineberg Algae Farm).
        // Kept a separate prefab and a separate menu item because it is regenerated far more
        // often than the terrain, and rebuilding a 2049^2 heightmap to move a buoy is absurd.
        var farmPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(
            "Packages/com.smarc.assets/Runtime/Prefabs/Environment/AlgaeFarm/KristinebergAlgaeFarm.prefab");
        if (farmPrefab != null)
        {
            var f = (GameObject)PrefabUtility.InstantiatePrefab(farmPrefab);
            f.transform.position = Vector3.zero;   // buoy coordinates are already scene metres
            Debug.Log("[Kristineberg] algae farm instanced");
        }
        else Debug.Log("[Kristineberg] no algae farm prefab yet — run SMARC -> Build Kristineberg Algae Farm");

        var seabedPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(
            "Packages/com.smarc.assets/Runtime/Prefabs/Environment/KristinebergSeabed.prefab");
        if (seabedPrefab != null)
        {
            var s = (GameObject)PrefabUtility.InstantiatePrefab(seabedPrefab);
            s.transform.position = Vector3.zero;
            Debug.Log("[Kristineberg] seabed dressing + current field instanced");
        }
        else Debug.Log("[Kristineberg] no seabed prefab yet — run SMARC -> Build Kristineberg Seabed");

        var dir = Path.GetDirectoryName(ScenePath);
        if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);
        EditorSceneManager.SaveScene(scene, ScenePath);
        Debug.Log("[Kristineberg] scene -> " + ScenePath);
    }
}
